//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashcardsGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashcardsGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _en_multiformABCDEFGHLONGLEE123 {
            get {
                object obj = ResourceManager.GetObject("_en_multiformABCDEFGHLONGLEE123", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _en_singleformABCDEFGHLONGLEE123 {
            get {
                object obj = ResourceManager.GetObject("_en_singleformABCDEFGHLONGLEE123", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _fr_multiformABCDEFGHLONGLEE123 {
            get {
                object obj = ResourceManager.GetObject("_fr_multiformABCDEFGHLONGLEE123", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _fr_singleformABCDEFGHLONGLEE123 {
            get {
                object obj = ResourceManager.GetObject("_fr_singleformABCDEFGHLONGLEE123", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*------------------------------------*\
        ///    GLOBAL STYLES
        ///\*------------------------------------*/
        ///
        ////* high level styles */
        ///html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _interface {
            get {
                return ResourceManager.GetString("_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _vn_singleformABCDEFGHLONGLEE123 {
            get {
                object obj = ResourceManager.GetObject("_vn_singleformABCDEFGHLONGLEE123", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anki {
            get {
                object obj = ResourceManager.GetObject("anki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btn_wordlist {
            get {
                object obj = ResourceManager.GetObject("btn_wordlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///@font-face{font-family:&apos;Open Sans&apos;;font-style:normal;font-weight:400;src:local(&apos;Open Sans&apos;),local(&apos;OpenSans&apos;),url(/external/fonts/OpenSans.woff?version=3.1.50) format(&apos;woff&apos;);unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2212,U+2215,U+E0FF,U+EFFD,U+F000}
        ///*{word-wrap:break-word;margin:0;padding:0;border:0;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;-ms-box-sizing:border-box;-o-box-sizing:border-box;box-sizing:border-box;font-weight:inherit;font- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string collins_common {
            get {
                return ResourceManager.GetString("collins_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *{margin:0;padding:0;border:0;text-indent:0}html{overflow-y:scroll}input,textarea,button{border:solid 1px #aaa}button,a{cursor:pointer}a,a:link,a:visited,a:active{color:inherit;text-decoration:none;-webkit-transition-property:background,border;-webkit-transition-duration:250ms}li{list-style-type:none}h1,h2,h3,h4,h5,h6{font-size:1em}body,select,input,textarea,optgroup,option,button{font-size:12px;font-family:Arial,Helvetica,sans-serif}body{background-color:#eff4f7}table{border-spacing:0;border-collapse:colla [rest of string was truncated]&quot;;.
        /// </summary>
        public static string common {
            get {
                return ResourceManager.GetString("common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dot {
            get {
                object obj = ResourceManager.GetObject("dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap enlarge_img {
            get {
                object obj = ResourceManager.GetObject("enlarge_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap entry_arrow {
            get {
                object obj = ResourceManager.GetObject("entry_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap entry_bullet {
            get {
                object obj = ResourceManager.GetObject("entry_bullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap entry_sqbullet {
            get {
                object obj = ResourceManager.GetObject("entry_sqbullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap external {
            get {
                object obj = ResourceManager.GetObject("external", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap go_to_top {
            get {
                object obj = ResourceManager.GetObject("go_to_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hidden {
            get {
                object obj = ResourceManager.GetObject("hidden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {padding:0px;margin:0px;font-family:Arial; font-size:10pt; font-weight:normal;background-color:#ecf5ff;}
        ///p, ul { margin-bottom: 20px;line-height: 1.6em;}
        ///header,footer,nav,section {display: block;}
        ///h1, h2, h3, h4, h5, h6 {font-size: 10pt; font-family:Arial; color: #000;}
        ///h1 {font-size: 11pt; margin:0px; padding:0px;}
        ///h2 {font-size: 11pt;font-weight:normal;padding-bottom: 0; margin-bottom: 0; }
        ///
        ///h3 {font-weight:normal;padding-bottom: 0; margin-bottom: 0; line-height:10px}
        ///h4 {font-size: 9pt;}
        ///h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_6_7 {
            get {
                object obj = ResourceManager.GetObject("Icon_6_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_7_4 {
            get {
                object obj = ResourceManager.GetObject("Icon_7_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_academic {
            get {
                object obj = ResourceManager.GetObject("icon_academic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_audio_bre {
            get {
                object obj = ResourceManager.GetObject("icon_audio_bre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_audio_name {
            get {
                object obj = ResourceManager.GetObject("icon_audio_name", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_ox3000 {
            get {
                object obj = ResourceManager.GetObject("icon_ox3000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_plus_minus {
            get {
                object obj = ResourceManager.GetObject("icon_plus_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_plus_minus_grey {
            get {
                object obj = ResourceManager.GetObject("icon_plus_minus_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_plus_minus_orange {
            get {
                object obj = ResourceManager.GetObject("icon_plus_minus_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_select_arrow_circle_blue {
            get {
                object obj = ResourceManager.GetObject("icon_select_arrow_circle_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons_right {
            get {
                object obj = ResourceManager.GetObject("icons_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login_bg {
            get {
                object obj = ResourceManager.GetObject("login_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #column-content{margin:0 0 0;padding:0;z-index:0}
        ///#content{margin:0;padding:0 1em 1.5em;position:relative;z-index:2;color:black;border-top:1px solid #88C0EC;border-right:none}#column-two{top:-35px;position:relative;float:left;margin:auto;width:250px}body{font:x-small sans-serif;color:black;margin:0;padding:0;font-size:12px}#globalWrapper{width:985px; background-color:#FFFFFF;margin:0 auto;padding:0}.visualClear{clear:both}table{font-size:100%;color:black;background-color:white}a{text-decoration:none;color: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string main_min {
            get {
                return ResourceManager.GetString("main_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minus_section {
            get {
                object obj = ResourceManager.GetObject("minus_section", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*------------------------------------*\
        ///    GLOBALLY DEFINED STYLES
        ///\*------------------------------------*/
        ///ol {
        ///    list-style-type: decimal;
        ///    padding-left: 20px;
        ///}
        ///
        ////*
        /// *********************************************
        /// * IDM new classes
        /// *********************************************
        /// */
        ///
        ////* Icons (nb: there are 2 types of &apos;icons&apos;, images and divs) */
        ///
        ///img.icon {
        ///    vertical-align: text-bottom;
        ///    margin-top: 0;
        ///    margin-right: 2px;
        ///    margin-left: 0;
        ///    margin-bottom: 0;
        ///}
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string oxford {
            get {
                return ResourceManager.GetString("oxford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plus_section {
            get {
                object obj = ResourceManager.GetObject("plus_section", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pvarr {
            get {
                object obj = ResourceManager.GetObject("pvarr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pvarr_blue {
            get {
                object obj = ResourceManager.GetObject("pvarr_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fimg {
        ///    max-width: 100%;
        ///}
        ///
        ///.toggle_hide {
        ///    display: none;
        ///}
        ///
        ////* responsive design initial features - same as desktop */
        ///.responsive_no_margin {
        ///    margin: 0px !important
        ///}
        ///
        ///.responsive_container {
        ///    clear: both;
        ///    margin-left: auto;
        ///    margin-right: auto;
        ///}
        ///
        ///.responsive_container::before,.responsive_container::after {
        ///    display: table;
        ///    content: &quot;&quot;;
        ///    line-height: 0;
        ///}
        ///
        ///.responsive_container::after {
        ///    clear: both;
        ///}
        ///
        ///.responsive_row {
        ///    clear: both;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string responsive {
            get {
                return ResourceManager.GetString("responsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_mag {
            get {
                object obj = ResourceManager.GetObject("search_mag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap usonly_audio {
            get {
                object obj = ResourceManager.GetObject("usonly_audio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
